---
title: "P8105 Midterm Project"
output: github_document
date: "2024-10-20"
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(rnoaa)
library(dplyr)
library(ggplot2)
library(readr)
library(janitor)
library(rvest)
library(httr)
```

```{r}
jan_2015_zillow = 
  read_csv("zillow/zhvi_2015.csv", show_col_types = FALSE) |>
  clean_names() |>
  drop_na() |>
  select(zip_code = region_name, everything()) 
```

```{r}
aug_2023_zillow = 
  read_csv("zillow/zhvi_2023.csv", show_col_types = FALSE) |>
  clean_names() |>
  drop_na()
```

```{r}
nyc_zip_codes_url = "https://p8105.com/data/zip_codes.html"

nyc_zip_codes = read_html(nyc_zip_codes_url)

table_nyc_zip_codes = 
nyc_zip_codes |>
  html_table() |>
  first() |>
  slice(-1) |>
  as_tibble()
```


```{r}
table_nyc_zip_codes <- table_nyc_zip_codes %>%
  mutate(Borough = case_when(
    County == "New York" ~ "Manhattan",
    County == "Kings" ~ "Brooklyn",
    County == "Bronx" ~ "Bronx",
    County == "Queens" ~ "Queens",
    County == "Richmond" ~ "Staten Island"
  )) %>%
  select(Zipcode = Zipcode, everything())

jan2015_zipcodes_df = 
  left_join(jan_2015_zillow, table_nyc_zip_codes, by = "Zipcode")

print(jan2015_zipcodes_df)
```

